import Head from "next/head";
import Nav from "./Navbar/Nav";

export default function Layout({ children, title, container }) {
  const time = () => new Date().getFullYear();

  return (
    <>
      <Head>
        <title>{title ? `${title} - Prime` : "Prime"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-between">
        <Nav />
        {container === true ? (
          <main className="max-w-[1000px] w-[95vw] m-auto mt-20 px-5">
            {children}
          </main>
        ) : (
          <main className="container m-auto mt-20 px-5">{children}</main>
        )}
        <footer className="flex justify-center items-center shadow-inner h-10">
          <p>Copyright &copy; {time()} Prime </p>
        </footer>
      </div>
    </>
  );
}
