export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const INIT_STORED_CART = "INIT_STORED_CART";
export const CART_COUNT_TOTALS = "CART_COUNT_TOTALS";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_RESET = "CART_RESET";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";
